name       : perl-test-exception
version    : 0.43
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/E/EX/EXODIST/Test-Exception-0.43.tar.gz : 156b13f07764f766d8b45a43728f2439af81a3512625438deab783b7883eb533
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Test::Exception - Test exception-based code
description: |
    Test::Exception - Test exception-based code
builddeps  :
    - perl-sub-uplevel
rundeps    :
    - perl-sub-uplevel
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
